name: Bump Formula versions and dependencies
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          # GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_TOKEN}}
          livecheck: true
          no_fork: true
          tap: gtaylor/baymesh
          formula: baymesh
