name: refresh Python Formulas

on: workflow_dispatch

jobs:
  refresh:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Run uname
        run: uname  -a

      - name: Update brew
        run: brew update && brew upgrade

      - name: Untap
        run: brew untap homebrew/cask && brew untap homebrew/core && brew uninstall openssl@1.1 ruby@3.0 && brew cleanup

      - name: Add tap
        run: brew tap gtaylor/baymesh

      - name: Remove old Formulas
        run: rm /opt/homebrew/Library/Taps/gtaylor/homebrew-baymesh/Formula/baymesh.rb

      - name: Run brew config
        run: brew config

      - name: Run brew doctor
        run: brew doctor --verbose

      - name: Regenerate Python Formulas
        run: cd /opt/homebrew/Library/Taps/gtaylor/homebrew-baymesh && ./scripts/regen-python-formulas.sh

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main
