name: refresh Python Formulas

on: workflow_dispatch

jobs:
  refresh:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Update brew
        run: brew update && brew developer on

      # Brew doctor freaks out about these being tapped.
      - name: Untap
        run: brew untap homebrew/cask homebrew/core

      # Not sure why this comes by default but brew doctor errors out here as well.
      - name: Remove legacy formula
        run: brew uninstall openssl@1.1 && brew cleanup

      - name: Add tap
        run: brew tap gtaylor/baymesh

      - name: Run brew config
        run: brew config

      - name: Run brew doctor
        run: brew doctor --verbose

      - name: Regenerate Python Formulas
        run: ./scripts/regen-python-formulas.sh
        working-directory: /opt/homebrew/Library/Taps/gtaylor/homebrew-baymesh

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main
